### ISSUE TITLE
Support to relative paths

### ISSUE THREAD

**Issue by wandecleya** [MaibornWolff/ts-arch#34]
Does the library have a way to consider relative import paths when is evaluating dependencies between folders? Or have the feature in the backlog to be implemented?

Something like:
```
import { EntryTypes } from '@constants/enums';
```

**Comment by torfmaster** [comment]
I haven't tested this but path aliases should be supported out-of-the-box (as typescript supports it). The only thing to consider is that all dependency checks use the path relative to the tsconfig.json of your project instead of the aliases and you have to use your rules in the right way.

**Comment by daniel-rodrigues-tw** [comment]
Same problem here.

 ```
beforeAll(() => {
    files = filesOfProject(__dirname + '/../../tsconfig.json');
  });
  // architecture tests can take a while to finish
  jest.setTimeout(60000);

  it('test A should not depend on the test B', async () => {
    const rule = files
      .inFolder('components/Atest/*')
      .shouldNot()
      .dependOnFiles()
      .inFolder('components/Btest/*');

    await expect(rule).toPassAsync();
  });
```

|Folders||
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/57457613/99724975-330d4980-2a93-11eb-98ce-3bc4f8eccb48.png) | ![image](https://user-images.githubusercontent.com/57457613/99725179-7b2c6c00-2a93-11eb-861a-789ac81f2058.png) |


With this import in Atest file, the test pass:
`import Btest from '@components/Btest/Btest';`

With this import in Atest file, the test fails, as expected:
`import Btest from '../Btest/Btest';`

Error: expected to pass
src/components/Atest/Atest.ts -> src/components/Btest/Btest.ts is not allowed
{"dependency":{"sourceLabel":"src/components/Atest/Atest.ts","targetLabel":"src/components/Btest/Btest.ts","cumulatedEdges":[{"source":"src/components/Atest/Atest.ts","target":"src/components/Btest/Btest.ts","external":false}]}}

Any idea what could be wrong?

tsconfig.json:
```
{
  "compilerOptions": {
    "paths": {
      "@components/*": ["./src/components/*"],
    },
    ...
  },
}
```

.babelrc:
```
"plugins": [
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "@components": "./src/components",
        }
      }
    ]
  ]
```

jest.config.js:
```
moduleNameMapper: {
    '@components/(.*)$': '<rootDir>/src/components/$1',
    '\\.scss$': 'identity-obj-proxy',
  },
```

**Comment by mrpatpat** [comment]
Thank you for the contributions. My expectation would be that it should actually work. There may be a bug or something. 
I need to take a detailed look at it.

**Comment by mrpatpat** [comment]
Hi again. 

I could reproduce the bug and locate the potential code for it but currently I am unable to work on it for today. This is a bug IMO.

**Comment by mrpatpat** [comment]
Update:

I started to dig deeper into the problem and found [this](https://github.com/microsoft/TypeScript/issues/10866) where it is stated that TS by itself does not interpret path-aliases since it is the job of a loader (correct me if I got it wrong). 
My minimal example is still without babel so I will try it next. 

![image](https://user-images.githubusercontent.com/2622069/100015396-2dd43580-2dd8-11eb-8eb6-23618e20e2cb.png)
Here we can see the paths the compiler tries to resolve to. It seems like it doesnt care about the paths field.

**Comment by wandecleya** [comment]
Do we have any news? This is really the only issue preventing us from adopt this super cool library!

**Comment by torfmaster** [comment]
Bad news: Typescript itself doesn't have any support for relative paths. 
However, good news: it seems to be relatively easy to add extra support for this using something like https://www.npmjs.com/package/@zerollup/ts-helpers. I'll be on a long train ride on Friday and will try to implement this.

**Comment by torfmaster** [comment]
@wandecleya I created a PR containing fixes for the absolute path problem. I would be interested in your feedback!

**Comment by torfmaster** [comment]
Ping @mrpatpat , can we merge this?
